# Generated by Django 4.1.3 on 2023-01-29 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0005_alter_contract_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=40)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('service_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AdvertisingConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertising_serivice', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='advertising_products.advertisingservice')),
                ('id_contract', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contracts.advertisingcontract')),
            ],
        ),
    ]
