# Generated by Django 4.1.3 on 2022-12-21 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('manager', 'manager'), ('operator', 'operator'), ('client', 'client')], default=None, max_length=12, null=True),
        ),
    ]
