# Generated by Django 4.1.3 on 2023-01-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_userroles_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userroles',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('manager', 'manager'), ('operator', 'operator'), ('client', 'client'), ('root', 'root')], default=None, max_length=20, null=True, unique=True),
        ),
    ]
