# Generated by Django 4.1.3 on 2023-01-29 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('energy_products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('penalty', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('date', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('in-house', 'in-house'), ('online', 'online'), ('bank', 'bank')], max_length=30, null=True)),
                ('payment_institution', models.CharField(max_length=50, null=True)),
                ('is_deposit', models.BooleanField(default=False)),
                ('service_paid', models.CharField(choices=[('energy consumption', 'energy consumption'), ('advertising consumption', 'advertising consumption')], max_length=50)),
                ('id_consumption', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment', to='energy_products.energyconsumptions')),
            ],
        ),
    ]
