# Generated by Django 4.1.3 on 2023-01-30 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('energy_products', '0001_initial'),
        ('advertising_products', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='id_consumption',
        ),
        migrations.AddField(
            model_name='payment',
            name='id_advertising_consumption',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment', to='advertising_products.advertisingconsumption'),
        ),
        migrations.AddField(
            model_name='payment',
            name='id_energy_consumption',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment', to='energy_products.energyconsumptions'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_institution',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('in-house', 'in-house'), ('online', 'online'), ('bank', 'bank')], default='unknown', max_length=30),
            preserve_default=False,
        ),
    ]
