# Generated by Django 4.1.3 on 2023-01-30 01:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_alter_contract_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateField(default=datetime.date(2023, 1, 30)),
        ),
    ]
