# Generated by Django 4.1.3 on 2023-01-20 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0003_contract_is_active_alter_contracttype_contract_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricityPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='EnergyConsumptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_kwh', models.IntegerField()),
                ('billing_period_starts', models.DateField()),
                ('billing_period_ends', models.DateField()),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField(null=True)),
                ('is_fully_paid', models.BooleanField(default=False)),
                ('id_contract', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contracts.energycontract')),
                ('price_kwh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='energy_products.electricityprice')),
            ],
        ),
    ]
