# Generated by Django 4.1.3 on 2023-01-12 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracttype',
            name='contract_type',
            field=models.CharField(choices=[('electric', 'electric'), ('advertising', 'advertising')], max_length=30, unique=True),
        ),
    ]
